# Generated by Django 5.1.6 on 2026-03-25 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_student_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='school.etablissement'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['etablissement', '-date'], name='expense_etab_date_idx'),
        ),
    ]
