# Generated by Django 5.1.6 on 2026-03-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0013_expense_etablissement_expense_expense_etab_date_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="conduite",
            field=models.DecimalField(decimal_places=2, default=18, max_digits=4),
        ),
    ]
