# Generated by Django 5.1.6 on 2026-08-03 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    """Rend la date d'inscription corrigeable.

    `auto_now_add` etait une contrainte applicative, pas une contrainte SQL:
    la colonne reste `date NOT NULL` et les dates deja enregistrees sont
    conservees telles quelles. Aucune reprise de donnees n'est necessaire,
    mais les fiches saisies apres coup portent toujours la date de saisie et
    devront etre corrigees a la main si l'ecole y tient.
    """

    dependencies = [
        ('school', '0030_alter_student_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
