# Generated by Django 5.1.6 on 2026-08-24 02:54

import apps.school.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_alter_student_enrollment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'label'],
            },
        ),
        migrations.CreateModel(
            name='LibraryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('position', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='school.librarycollection')),
            ],
            options={
                'ordering': ['position', 'name'],
                'unique_together': {('collection', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LibraryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.school.models.library_document_path)),
                ('source_url', models.URLField(max_length=500, unique=True)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('import_error', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='school.librarycategory')),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
    ]
