# Generated by Django 5.1.6 on 2026-08-24 04:47

import apps.school.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_librarycollection_librarycategory_librarydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarydocument',
            name='file',
            field=models.FileField(blank=True, max_length=400, null=True, upload_to=apps.school.models.library_document_path),
        ),
    ]
