# Generated by Django 5.1.6 on 2026-08-26 02:06

from django.db import migrations, models


# Libelles libres deja saisis -> motif du referentiel. La cle est comparee en
# minuscules et sans espaces de bord; ce qui ne correspond a rien devient
# « autre », la description gardant le detail.
CORRESPONDANCES = {
    "indiscipline": "indiscipline",
    "retard": "retard",
    "retards": "retard",
    "arrivee tardive": "retard",
    "arrivée tardive": "retard",
    "absence": "absence_injustifiee",
    "absence injustifiee": "absence_injustifiee",
    "absence injustifiée": "absence_injustifiee",
    "violence": "violence",
    "bagarre": "violence",
    "triche": "triche",
    "tricherie": "triche",
    "fraude": "triche",
    "degradation": "degradation",
    "dégradation": "degradation",
    "degradation de materiel": "degradation",
    "tenue": "tenue",
    "tenue non conforme": "tenue",
    "insolence": "insolence",
    "autre": "autre",
}


def normaliser_categories(apps, schema_editor):
    """Aligne les motifs existants sur le referentiel.

    Sans cette passe, les lignes deja en base porteraient un libelle que le
    serializer refuserait desormais: la fiche s'affichait mais toute
    modification echouait sur un champ que personne n'avait touche.
    """
    DisciplineIncident = apps.get_model("school", "DisciplineIncident")
    for incident in DisciplineIncident.objects.all().iterator():
        cle = (incident.category or "").strip().lower()
        cible = CORRESPONDANCES.get(cle, "autre")
        if incident.category != cible:
            DisciplineIncident.objects.filter(pk=incident.pk).update(category=cible)


def dater_les_clotures(apps, schema_editor):
    """Donne une date de cloture aux incidents deja traites.

    `updated_at` est la meilleure approximation disponible: c'est la derniere
    fois que la ligne a bouge, et pour un incident clos c'est en pratique sa
    cloture. Laisser le champ vide aurait fait passer ces incidents pour
    non traites dans tout calcul de delai.
    """
    DisciplineIncident = apps.get_model("school", "DisciplineIncident")
    for incident in (
        DisciplineIncident.objects.filter(status="resolved", resolved_at__isnull=True)
        .only("pk", "updated_at")
        .iterator()
    ):
        DisciplineIncident.objects.filter(pk=incident.pk).update(
            resolved_at=incident.updated_at
        )


def sans_retour(apps, schema_editor):
    """Rien a defaire: les deux passes ne detruisent aucune information."""


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_book_published_year_book_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplineincident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disciplineincident',
            name='category',
            field=models.CharField(choices=[('indiscipline', 'Indiscipline'), ('retard', 'Retard'), ('absence_injustifiee', 'Absence injustifiee'), ('violence', 'Violence'), ('triche', 'Triche'), ('degradation', 'Degradation de materiel'), ('tenue', 'Tenue non conforme'), ('insolence', 'Insolence'), ('autre', 'Autre')], default='indiscipline', max_length=120),
        ),
        migrations.RunPython(normaliser_categories, sans_retour),
        migrations.RunPython(dater_les_clotures, sans_retour),
    ]
