# Generated by Django 5.1.6 on 2026-08-27 16:59

import django.db.models.deletion
from django.db import migrations, models


def eclater_par_etablissement(apps, schema_editor):
    """Donne a chaque etablissement ses propres annees scolaires.

    Une seule « 2025-2026 » servait les quatre ecoles. Chacune recoit
    desormais la sienne, aux memes dates, et tout ce qui portait l'annee
    partagee est reaffecte a l'annee de son etablissement.

    L'annee d'origine n'est supprimee que si plus rien ne la reference: un
    objet dont l'etablissement reste indeterminable doit rester rattache a
    quelque chose plutot que de perdre son annee.
    """
    AcademicYear = apps.get_model("school", "AcademicYear")
    Etablissement = apps.get_model("school", "Etablissement")
    ClassRoom = apps.get_model("school", "ClassRoom")
    Grade = apps.get_model("school", "Grade")
    GradeValidation = apps.get_model("school", "GradeValidation")
    StudentFee = apps.get_model("school", "StudentFee")
    StudentAcademicHistory = apps.get_model("school", "StudentAcademicHistory")
    CanteenSubscription = apps.get_model("school", "CanteenSubscription")
    ExamSession = apps.get_model("school", "ExamSession")
    ExamPlanning = apps.get_model("school", "ExamPlanning")
    ExamResult = apps.get_model("school", "ExamResult")
    PromotionRun = apps.get_model("school", "PromotionRun")

    etablissements = list(Etablissement.objects.order_by("id"))
    if not etablissements:
        return

    anciennes = list(AcademicYear.objects.filter(etablissement__isnull=True))
    if not anciennes:
        return

    # (ancienne annee, etablissement) -> nouvelle annee
    nouvelles = {}
    for ancienne in anciennes:
        for etablissement in etablissements:
            copie, _ = AcademicYear.objects.get_or_create(
                name=ancienne.name,
                etablissement=etablissement,
                defaults={
                    "start_date": ancienne.start_date,
                    "end_date": ancienne.end_date,
                    "is_active": ancienne.is_active,
                    "is_closed": getattr(ancienne, "is_closed", False),
                },
            )
            nouvelles[(ancienne.id, etablissement.id)] = copie

    def cible(ancienne_id, etablissement_id):
        return nouvelles.get((ancienne_id, etablissement_id))

    # --- Les classes portent l'etablissement: elles ouvrent la voie -------
    for classe in ClassRoom.objects.filter(
        academic_year__etablissement__isnull=True
    ).select_related("academic_year"):
        cible_annee = cible(classe.academic_year_id, classe.etablissement_id)
        if cible_annee is not None:
            ClassRoom.objects.filter(pk=classe.pk).update(academic_year=cible_annee)

    # --- Puis ce qui se rattache par la classe ---------------------------
    for modele in (Grade, GradeValidation, StudentAcademicHistory):
        for ligne in modele.objects.filter(
            academic_year__etablissement__isnull=True
        ).select_related("classroom"):
            classe = ligne.classroom
            if classe is None:
                continue
            cible_annee = cible(ligne.academic_year_id, classe.etablissement_id)
            if cible_annee is not None:
                modele.objects.filter(pk=ligne.pk).update(academic_year=cible_annee)

    # --- Puis ce qui se rattache par l'eleve ------------------------------
    for modele in (StudentFee, CanteenSubscription):
        for ligne in modele.objects.filter(
            academic_year__etablissement__isnull=True
        ).select_related("student"):
            eleve = ligne.student
            if eleve is None:
                continue
            cible_annee = cible(ligne.academic_year_id, eleve.etablissement_id)
            if cible_annee is not None:
                modele.objects.filter(pk=ligne.pk).update(academic_year=cible_annee)

    # --- Les sessions d'examen n'ont pas d'etablissement -----------------
    # Elles se rattachent par les classes qu'elles convoquent, et a defaut
    # par les eleves dont elles portent les resultats: une session peut
    # avoir ete saisie sans planning prealable, et elle porte alors des
    # notes qu'il ne faut pas laisser dans une annee sans ecole.
    for session in ExamSession.objects.filter(academic_year__etablissement__isnull=True):
        etablissement_ids = set(
            ExamPlanning.objects.filter(session=session)
            .values_list("classroom__etablissement_id", flat=True)
        )
        etablissement_ids.discard(None)

        etablissement_vise = None
        if len(etablissement_ids) == 1:
            etablissement_vise = etablissement_ids.pop()
        else:
            # A defaut de planning, l'ecole qui fournit le gros des
            # candidats. Une session d'un ancien fonds peut porter des
            # resultats de plusieurs ecoles, du temps ou rien ne les
            # cloisonnait; la laisser sans etablissement la rendrait
            # invisible partout, avec ses notes.
            comptes = {}
            for etablissement_id in ExamResult.objects.filter(
                session=session
            ).values_list("student__etablissement_id", flat=True):
                if etablissement_id is None:
                    continue
                comptes[etablissement_id] = comptes.get(etablissement_id, 0) + 1
            if comptes:
                etablissement_vise = max(comptes, key=comptes.get)

        if etablissement_vise is None:
            continue
        cible_annee = cible(session.academic_year_id, etablissement_vise)
        if cible_annee is not None:
            ExamSession.objects.filter(pk=session.pk).update(academic_year=cible_annee)

    # --- Les passations portent deux annees, et leur etablissement -------
    # Elles le declarent elles-memes: c'est la seule table ou la cible se
    # lit sans passer par une classe ou un eleve.
    for run in PromotionRun.objects.filter(etablissement__isnull=False):
        champs = {}
        for champ in ("source_academic_year_id", "target_academic_year_id"):
            annee_id = getattr(run, champ)
            if annee_id is None:
                continue
            cible_annee = cible(annee_id, run.etablissement_id)
            if cible_annee is not None:
                champs[champ] = cible_annee.id
        if champs:
            PromotionRun.objects.filter(pk=run.pk).update(**champs)

    # --- L'ancienne annee se retire de la saisie -------------------------
    # Elle n'appartient a aucune ecole: elle ne peut plus etre l'annee
    # courante de personne. Sa suppression, quand elle est vide, attend la
    # migration 0046: un DELETE ici laisserait des declencheurs de cle
    # etrangere en attente, et Postgres refuserait de creer les index de
    # cette meme migration.
    for ancienne in anciennes:
        AcademicYear.objects.filter(pk=ancienne.id).update(is_active=False)


def sans_retour(apps, schema_editor):
    """Rien a defaire: l'eclatement ne detruit aucune information."""


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0043_availabilitycampaign_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-start_date', '-id']},
        ),
        migrations.AddField(
            model_name='academicyear',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_years', to='school.etablissement'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('name', 'etablissement')},
        ),
        migrations.RunPython(eclater_par_etablissement, sans_retour),
    ]
