# Generated by Django 5.1.6 on 2026-08-27 23:00

import django.db.models.deletion
from django.db import migrations, models


def _index_des_annees(AcademicYear):
    """Annees par etablissement, pretes a etre interrogees par date."""
    par_etablissement = {}
    for annee in AcademicYear.objects.exclude(etablissement__isnull=True):
        par_etablissement.setdefault(annee.etablissement_id, []).append(annee)
    return par_etablissement


def _annee_pour(index, etablissement_id, jour):
    """L'annee de cet etablissement qui contient ce jour, s'il y en a une.

    Les annees d'une meme ecole ne se chevauchent pas -- une contrainte le
    garantit depuis 0045 -- donc au plus une correspond.
    """
    if etablissement_id is None or jour is None:
        return None
    for annee in index.get(etablissement_id, ()):
        if annee.start_date <= jour <= annee.end_date:
            return annee
    return None


def rattacher_aux_annees(apps, schema_editor):
    """Donne son annee scolaire a ce qui n'avait qu'une date.

    Absences, incidents, emargements, depenses et paies ne portaient que le
    jour: le dossier d'un eleve affichait ses absences de toutes les annees
    melangees, et rien ne les separait une fois l'eleve passe en classe
    superieure.

    Une ligne dont la date ne tombe dans aucune annee connue reste sans
    rattachement: inventer une annee serait pire que l'absence de reponse.
    """
    AcademicYear = apps.get_model("school", "AcademicYear")
    index = _index_des_annees(AcademicYear)
    if not index:
        return

    Attendance = apps.get_model("school", "Attendance")
    DisciplineIncident = apps.get_model("school", "DisciplineIncident")
    TeacherAttendance = apps.get_model("school", "TeacherAttendance")
    TeacherPayroll = apps.get_model("school", "TeacherPayroll")
    Expense = apps.get_model("school", "Expense")

    # (modele, champ de date, chemin vers l'etablissement)
    SOURCES = (
        (Attendance, "date", ("student", "etablissement_id")),
        (DisciplineIncident, "incident_date", ("student", "etablissement_id")),
        (TeacherAttendance, "date", ("teacher", "etablissement_id")),
        (TeacherPayroll, "month", ("teacher", "etablissement_id")),
        (Expense, "date", ("etablissement_id",)),
    )

    for modele, champ_date, chemin in SOURCES:
        lignes = modele.objects.filter(academic_year__isnull=True)
        if len(chemin) > 1:
            lignes = lignes.select_related(chemin[0])

        for ligne in lignes.iterator():
            porteur = ligne
            for partie in chemin[:-1]:
                porteur = getattr(porteur, partie, None)
                if porteur is None:
                    break
            if porteur is None:
                continue

            etablissement_id = getattr(porteur, chemin[-1], None)
            annee = _annee_pour(index, etablissement_id, getattr(ligne, champ_date, None))
            if annee is not None:
                modele.objects.filter(pk=ligne.pk).update(academic_year=annee)


def sans_retour(apps, schema_editor):
    """Rien a defaire: le rattachement n'ecrase aucune donnee."""



class Migration(migrations.Migration):

    dependencies = [
        ('school', '0048_matricules_manquants'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='school.academicyear'),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='school.academicyear'),
        ),
        migrations.AddField(
            model_name='expense',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='school.academicyear'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='school.academicyear'),
        ),
        migrations.AddField(
            model_name='teacherpayroll',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='school.academicyear'),
        ),
        migrations.RunPython(rattacher_aux_annees, sans_retour),
    ]
