# Generated by Django 5.1.6 on 2026-09-04 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0052_codes_de_classe_uniformises'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='whatsapp_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='whatsapp_consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='BulletinDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=20)),
                ('channel', models.CharField(choices=[('manual_link', 'Lien WhatsApp assisté'), ('cloud_api', 'WhatsApp Cloud API')], default='manual_link', max_length=20)),
                ('status', models.CharField(choices=[('prepared', 'Préparé'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('read', 'Consulté')], default='prepared', max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletin_deliveries', to='school.academicyear')),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulletin_deliveries', to='school.etablissement')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletin_deliveries', to='school.parentprofile')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_bulletin_deliveries', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_deliveries', to='school.student')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['student', 'academic_year', 'term'], name='bulletindeliv_stu_year_idx'), models.Index(fields=['etablissement', 'status'], name='bulletindeliv_etab_stat_idx')],
            },
        ),
    ]
