# Generated by Django 5.1.6 on 2026-09-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0055_validation_des_bulletins'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='etablissements/couvertures/'),
        ),
    ]
