# Generated by Django 5.1.6 on 2026-09-08 01:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0057_bilan_par_trimestre_et_coefficient_conduite'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_type', models.CharField(choices=[('registration', 'Frais inscription'), ('monthly', 'Frais mensuels'), ('exam', 'Frais examen')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('first_due_date', models.DateField()),
                ('occurrences', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_schedules', to='school.academicyear')),
                ('classroom', models.ForeignKey(blank=True, help_text="Vide: le bareme s'applique a toutes les classes de l'annee.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_schedules', to='school.classroom')),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_schedules', to='school.etablissement')),
            ],
            options={
                'ordering': ('classroom__name', 'fee_type', 'first_due_date'),
            },
        ),
        migrations.AddField(
            model_name='studentfee',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='school.feeschedule'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', False)), fields=('student', 'schedule', 'due_date'), name='frais_unique_par_echeance_de_bareme'),
        ),
        migrations.AddIndex(
            model_name='feeschedule',
            index=models.Index(fields=['academic_year', 'classroom'], name='feesched_year_class_idx'),
        ),
    ]
