# Generated by Django 5.1.6 on 2026-09-08 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0059_publication_des_resultats_d_examen'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='weekly_slots',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
