# Generated by Django 5.1.6 on 2026-09-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0060_volume_horaire_des_matieres'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotiondecision',
            name='average_matieres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
