# Generated by Django 5.1.6 on 2026-09-10 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0061_moyenne_des_matieres_a_la_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
