# Generated by Django 5.1.6 on 2026-09-12 01:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """L'inscription conditionnee au paiement, pour qui la demande.

    Le statut prend « validee » par defaut, donc toutes les fiches
    existantes. C'est voulu: la regle est decochee au depart, et une base
    reprise dont les eleves passeraient tous en attente ne pourrait plus
    imprimer un seul bulletin le lendemain de la mise a jour.
    """


    dependencies = [
        ('school', '0062_heures_d_absence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='inscription_exige_paiement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='inscription_montant_minimum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='student',
            name='inscription_exempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='inscription_exempted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_exemptees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='inscription_exempted_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='inscription_status',
            field=models.CharField(choices=[('en_attente', 'Inscription en attente'), ('validee', 'Inscription validee'), ('exemptee', "Dispense d'inscription")], default='validee', max_length=12),
        ),
    ]
