# Generated by Django 5.1.6 on 2026-09-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0063_inscription_conditionnee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='employee_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
