# Generated by Django 5.1.6 on 2026-09-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0064_matricule_enseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='mot_de_passe_eleve_modele',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='student',
            name='lien_parente',
            field=models.CharField(blank=True, choices=[('pere', 'Père'), ('mere', 'Mère'), ('tuteur', 'Tuteur')], max_length=10),
        ),
    ]
