# Generated by Django 5.1.6 on 2026-09-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0065_etablissement_mot_de_passe_eleve_modele_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='mot_de_passe_parent_modele',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
