FROM ghcr.io/cirruslabs/flutter:stable AS build

WORKDIR /app
COPY . .
RUN flutter pub get
RUN flutter build web --release --pwa-strategy=none --dart-define=API_BASE_URL=https://gestion-school-staging-api.onrender.com/api

FROM nginx:1.27-alpine
COPY nginx.web.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build/web /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
