FROM ghcr.io/cirruslabs/flutter:stable AS build

WORKDIR /app
COPY . .
RUN flutter pub get
RUN flutter build web --release --pwa-strategy=none --dart-define=API_BASE_URL=https://gestion-school-jkzf.onrender.com/api

FROM nginx:1.27-alpine
ENV PORT=80
COPY nginx.web.conf /etc/nginx/templates/default.conf.template
COPY --from=build /app/build/web /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
