# Generated by Django 5.1.6 on 2026-09-03 00:50

from django.db import migrations, models


def poser_l_identite_actuelle(apps, schema_editor):
    """Reprend ce que le code affichait en dur.

    Sans cela, la premiere ouverture apres deploiement montrerait un ecran de
    connexion sans nom d'ecole ni telephone: la migration ne doit rien
    changer a ce que les utilisateurs voient aujourd'hui.
    """
    Personnalisation = apps.get_model("common", "PersonnalisationPlateforme")
    Personnalisation.objects.update_or_create(
        pk=1,
        defaults={
            "nom_application": "GESTION LTOB",
            "nom_ecole": "LYCÉE TECHNIQUE OUMAR BAH",
            "sigle": "LTOB",
            "telephone": "78 78 59 13 / 66 74 22 32",
        },
    )


def rien_a_defaire(apps, schema_editor):
    """La ligne unique reste: la supprimer priverait l'ecran de son identite."""


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_backuparchive_restore_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnalisationPlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_application', models.CharField(default='GESTION SCOLAIRE', help_text="Titre de l'onglet du navigateur et de l'application.", max_length=80)),
                ('nom_ecole', models.CharField(default='', help_text="Nom complet, affiche sur l'ecran de connexion.", max_length=150)),
                ('sigle', models.CharField(blank=True, help_text='Abrege, utilise la ou la place manque.', max_length=20)),
                ('logo', models.ImageField(blank=True, help_text="Affiche sur l'ecran de connexion et le portail.", null=True, upload_to='personnalisation/')),
                ('telephone', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('titre_connexion', models.CharField(blank=True, max_length=120)),
                ('sous_titre_connexion', models.CharField(blank=True, max_length=200)),
                ('titre_portail', models.CharField(blank=True, max_length=120)),
                ('sous_titre_portail', models.CharField(blank=True, max_length=200)),
                ('message_accueil', models.TextField(blank=True, help_text='Phrase libre affichee sous le titre du portail.')),
                ('pied_de_page', models.TextField(blank=True)),
                ('couleur_principale', models.CharField(default='#6D5BFF', help_text="Couleur d'accent, au format #RRGGBB.", max_length=7)),
            ],
            options={
                'verbose_name': 'Personnalisation de la plateforme',
                'verbose_name_plural': 'Personnalisation de la plateforme',
            },
        ),
            migrations.RunPython(poser_l_identite_actuelle, rien_a_defaire),
    ]
