# Generated by Django 5.1.6 on 2026-09-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_personnalisationplateforme'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnalisationplateforme',
            name='image_fond',
            field=models.ImageField(blank=True, help_text='Image de fond du portail et de la connexion, sous un voile sombre. Large plutot que haute, 1600 px minimum.', null=True, upload_to='personnalisation/fonds/'),
        ),
    ]
