# Generated by Django 5.1.6 on 2026-09-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_jetons_d_appareil'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuparchive',
            name='build_phase',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='backuparchive',
            name='build_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backuparchive',
            name='build_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backuparchive',
            name='bytes_done',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backuparchive',
            name='bytes_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backuparchive',
            name='include_library_documents',
            field=models.BooleanField(default=False),
        ),
    ]
