# Generated by Django 5.1.6 on 2026-09-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_avancement_de_sauvegarde'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuparchive',
            name='restore_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
