# Generated by Django 5.1.6 on 2026-09-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_debut_de_restauration'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnalisationplateforme',
            name='imposer_changement_mot_de_passe',
            field=models.BooleanField(default=True, help_text="L'élève doit choisir son propre mot de passe à sa première connexion. Décocher laisse le mot de passe remis valable indéfiniment, et il se devine à partir d'un seul exemple."),
        ),
        migrations.AddField(
            model_name='personnalisationplateforme',
            name='mot_de_passe_eleve_modele',
            field=models.CharField(default='{matricule}', help_text='Modèle du mot de passe remis aux familles. Jetons disponibles : {matricule}, {annee}, {sigle}, {nom}, {prenom}. Une école peut avoir le sien, sur sa propre fiche.', max_length=60),
        ),
    ]
