# Generated by Django 5.1.6 on 2026-09-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_personnalisationplateforme_imposer_changement_mot_de_passe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnalisationplateforme',
            name='mot_de_passe_parent_modele',
            field=models.CharField(default='{telephone}', help_text='Modèle du mot de passe remis au parent. Jetons disponibles : {telephone}, {annee}, {sigle}, {nom}, {prenom}. Une école peut avoir le sien, sur sa propre fiche.', max_length=60),
        ),
        migrations.AlterField(
            model_name='personnalisationplateforme',
            name='imposer_changement_mot_de_passe',
            field=models.BooleanField(default=True, help_text="L'élève et le parent doivent choisir leur propre mot de passe à leur première connexion. Décocher laisse le mot de passe remis valable indéfiniment, et il se devine à partir d'un seul exemple."),
        ),
    ]
