services:
  db:
    image: mysql:8.4
    container_name: gestion_school_db
    environment:
      MYSQL_DATABASE: gestion_school
      MYSQL_USER: gestion_user
      MYSQL_PASSWORD: gestion_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: gestion_school_redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ../backend
    container_name: gestion_school_backend
    env_file:
      - ../backend/.env.example
    volumes:
      - ../backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"

  worker:
    build:
      context: ../backend
    container_name: gestion_school_worker
    command: celery -A config worker -l info
    env_file:
      - ../backend/.env.example
    volumes:
      - ../backend:/app
    depends_on:
      - backend
      - redis

  beat:
    build:
      context: ../backend
    container_name: gestion_school_beat
    command: celery -A config beat -l info
    env_file:
      - ../backend/.env.example
    volumes:
      - ../backend:/app
    depends_on:
      - backend
      - redis

volumes:
  mysql_data:
