# Generated by Django 5.1.6 on 2026-03-19 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('school', '0010_etablissement_book_etablissement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='school.etablissement'),
        ),
    ]
