# Generated by Django 5.1.6 on 2026-09-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_update_user_roles_censor_promoter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doit_changer_mot_de_passe',
            field=models.BooleanField(default=False),
        ),
    ]
