# Generated by Django 5.1.6 on 2026-04-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
