# Generated by Django 5.1.6 on 2026-08-31 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    """Ouvre le fil aux appels d'attention.

    Un appel fait surgir la fenetre de discussion chez le destinataire; il
    laisse desormais sa trace dans la conversation, au lieu de disparaitre
    sans laisser savoir qui a interrompu qui.
    """


    dependencies = [
        ('chat', '0004_chatmessage_attachment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texte'), ('file', 'Fichier'), ('attention', "Appel d'attention")], default='text', max_length=10),
        ),
    ]
