# Generated by Django 5.1.6 on 2026-08-31 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Rend les messages retirables et corrigibles.

    Un message parti dans le mauvais groupe y restait a vie. On efface
    desormais son contenu en gardant sa ligne et le nom de qui l'a retire:
    supprimer la ligne laisserait un trou inexplicable dans le fil.
    """


    dependencies = [
        ('chat', '0005_alter_chatmessage_message_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages_supprimes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
