# Generated by Django 5.1.6 on 2026-08-31 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Permet de repondre a un message precis.

    Dans un groupe actif, sans citation on ne sait plus a quoi repond quoi:
    trois questions posees, une reponse « oui », et personne ne sait laquelle.
    """


    dependencies = [
        ('chat', '0006_chatmessage_deleted_at_chatmessage_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.chatmessage'),
        ),
    ]
